### ISSUE TITLE
User can search for a recipe 

### ISSUE THREAD

**Issue by tran-christopher** [tran-christopher/Ajax-Project#1]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to input a search criteria in the search bar and have a list of all recipes matching that criteria returned to them.

## 🖼️ Wireframes

![Home Page (Desktop Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/23db4b42-986a-4096-a262-94d0cc42f853)

![Home Page (Mobile Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/4e0e322a-66e6-48f5-9fef-a9374dbfdc20)

![Search Results (Desktop Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/c3fac40d-527c-48e3-b189-f1bf7e748890)

![Search Results Page (Mobile Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/98c4c6ea-8583-4d6c-a4b6-31915afd8a82)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In HTML, add the header for the home page
  - [x] Title "DishDiscover" in top left
  - [x] Three tabs to the right of title: "Home", "Recipes", "Browse"
  - [x] Input to the right of the tabs where user can type out the criteria they wish to search through
- [x] Add the body using same images and copying the code that was used for the top search bar
- [x] Format page with CSS to match figma
- [x] Create page where results will be displayed, copying the header from home page and adding "Search Results" title underneath
- [x] Get data user will be requesting through API
  - [x] Query for search bar elements 
  - [x] Add an eventListener that will loop through the data and return recipes that match the search criteria when the user searches 
- [x] Display data on search results page 
  - [x] Render a dom tree for the returned data 
  - [x] Append the dom tree to the page 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
