### ISSUE TITLE
User can view image/ingredients/instructions/nutritional info of recipe 

### ISSUE THREAD

**Issue by tran-christopher** [tran-christopher/Ajax-Project#2]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view an image and information about a recipe when selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Recipe Selected (Desktop Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/afc01e10-e9d0-44ec-bc22-b3909f1b3eb9)
![Recipe Selected (Mobile Wireframe)](https://github.com/tran-christopher/Ajax-Project/assets/145728509/65a18722-c5cd-49fc-ada7-f384b6dba6f5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for recipe selected page
- [x] Define a viewSwap function that will display/hide different views depending on what's been selected
- [x] Update both search bar callbacks to switch to Search Results page when a search is submitted
- [x] Update/define callback to loop through recipe clicked on to display info on recipe selected page
- [x] Update/define callback to render new dom tree to be displayed on recipe selected page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
